/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 11/05/2010, 02:16:45 PM
 */

package co.edu.eam.biblioteca.vista;

import java.sql.SQLException;

import co.edu.eam.ingesoft.desarrollo.biblioteca.persistencia.utilidades.AdministradorConexionJDBC;

/**
 *
 * @author Camilo Andres
 */
public class Principal extends javax.swing.JFrame {

   
    /** Creates new form Principal 
     * @throws SQLException */
    public Principal() throws SQLException {
     
        	initComponents();
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanel = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        bPrestar = new javax.swing.JButton();
        bBuscarUsuario = new javax.swing.JButton();
        bBuscarLibro = new javax.swing.JButton();
        bEditorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSAlir = new javax.swing.JMenuItem();
        mnuItemPrestamo = new javax.swing.JMenu();
        MnuCrear = new javax.swing.JMenu();
        mnuItemCrearLobro = new javax.swing.JMenuItem();
        mnuItemCrearEditorial = new javax.swing.JMenuItem();
        mnuItemCrearAutor = new javax.swing.JMenuItem();
        mnuItemCrearUsuario = new javax.swing.JMenuItem();
        mnuItemPrestar = new javax.swing.JMenuItem();
        mnuItemCOsnultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        bPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Public_32x32-32 (2).png"))); // NOI18N
        bPrestar.setFocusable(false);
        bPrestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bPrestar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrestarActionPerformed(evt);
            }
        });
        jToolBar1.add(bPrestar);

        bBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buddy-Green.png"))); // NOI18N
        bBuscarUsuario.setFocusable(false);
        bBuscarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(bBuscarUsuario);

        bBuscarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Address-Book_24x24-32.png"))); // NOI18N
        bBuscarLibro.setFocusable(false);
        bBuscarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBuscarLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarLibroActionPerformed(evt);
            }
        });
        jToolBar1.add(bBuscarLibro);

        bEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Help.png"))); // NOI18N
        bEditorial.setFocusable(false);
        bEditorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEditorial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditorialActionPerformed(evt);
            }
        });
        jToolBar1.add(bEditorial);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User-Male.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maintenance_32x32-32.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jMenu1.setText("Archivo");

        mnuSAlir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuSAlir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete_32x32-32.png"))); // NOI18N
        mnuSAlir.setText("Salir");
        mnuSAlir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSAlirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSAlir);

        jMenuBar1.add(jMenu1);

        mnuItemPrestamo.setText("Operaciones");
        mnuItemPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPrestamoActionPerformed(evt);
            }
        });

        MnuCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Document.png"))); // NOI18N
        MnuCrear.setText("Crear/Buscar");

        mnuItemCrearLobro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCrearLobro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Address-Book_24x24-32.png"))); // NOI18N
        mnuItemCrearLobro.setText("Libro");
        mnuItemCrearLobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCrearLobroActionPerformed(evt);
            }
        });
        MnuCrear.add(mnuItemCrearLobro);

        mnuItemCrearEditorial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCrearEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Help.png"))); // NOI18N
        mnuItemCrearEditorial.setText("Editorial");
        mnuItemCrearEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCrearEditorialActionPerformed(evt);
            }
        });
        MnuCrear.add(mnuItemCrearEditorial);

        mnuItemCrearAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCrearAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User-Male.png"))); // NOI18N
        mnuItemCrearAutor.setText("Autor");
        mnuItemCrearAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCrearAutorActionPerformed(evt);
            }
        });
        MnuCrear.add(mnuItemCrearAutor);

        mnuItemCrearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buddy-Green.png"))); // NOI18N
        mnuItemCrearUsuario.setText("Usuario");
        mnuItemCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCrearUsuarioActionPerformed(evt);
            }
        });
        MnuCrear.add(mnuItemCrearUsuario);

        mnuItemPrestamo.add(MnuCrear);

        mnuItemPrestar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Public_32x32-32 (2).png"))); // NOI18N
        mnuItemPrestar.setText("Prestar");
        mnuItemPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPrestarActionPerformed(evt);
            }
        });
        mnuItemPrestamo.add(mnuItemPrestar);

        mnuItemCOsnultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuItemCOsnultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Maintenance_32x32-32.png"))); // NOI18N
        mnuItemCOsnultas.setText("Consultas");
        mnuItemCOsnultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCOsnultasActionPerformed(evt);
            }
        });
        mnuItemPrestamo.add(mnuItemCOsnultas);

        jMenuBar1.add(mnuItemPrestamo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
            .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrestarActionPerformed
        // TODO add your handling code here:
        VentanaPrestamos presta=new VentanaPrestamos();
        desktopPanel.add(presta);
    }//GEN-LAST:event_bPrestarActionPerformed

    private void mnuItemCrearLobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCrearLobroActionPerformed
        // TODO add your handling code here:
        desktopPanel.add(new VentanaCrearBuscarLibro());
    }//GEN-LAST:event_mnuItemCrearLobroActionPerformed

    private void mnuItemPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPrestamoActionPerformed
       
    }//GEN-LAST:event_mnuItemPrestamoActionPerformed

    private void mnuItemPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPrestarActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         // TODO add your handling code here:
        VentanaPrestamos presta=new VentanaPrestamos();
        desktopPanel.add(presta);
    }//GEN-LAST:event_mnuItemPrestarActionPerformed

    private void mnuSAlirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSAlirActionPerformed

        System.exit(0);;
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSAlirActionPerformed

    private void bBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarUsuarioActionPerformed
        // TODO add your handling code here: VentanaPrestamos presta=new VentanaPrestamos(biblio);
        desktopPanel.add(new VentanaUsuario());
    }//GEN-LAST:event_bBuscarUsuarioActionPerformed

    private void mnuItemCrearEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCrearEditorialActionPerformed
        // TODO add your handling code here:
        desktopPanel.add(new VentanaCrearBuscarEditorial());
    }//GEN-LAST:event_mnuItemCrearEditorialActionPerformed

    private void bEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditorialActionPerformed
        // TODO add your handling code here:
         desktopPanel.add(new VentanaCrearBuscarEditorial());
    }//GEN-LAST:event_bEditorialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         desktopPanel.add(new VentanaCrearBuscarAutor());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          desktopPanel.add(new VentanaConsultas());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnuItemCOsnultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCOsnultasActionPerformed
        // TODO add your handling code here:
          desktopPanel.add(new VentanaConsultas());
    }//GEN-LAST:event_mnuItemCOsnultasActionPerformed

    private void mnuItemCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCrearUsuarioActionPerformed
        // TODO add your handling code here:
         desktopPanel.add(new VentanaUsuario());

    }//GEN-LAST:event_mnuItemCrearUsuarioActionPerformed

    private void bBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarLibroActionPerformed
        // TODO add your handling code here:
         desktopPanel.add(new VentanaCrearBuscarLibro());
    }//GEN-LAST:event_bBuscarLibroActionPerformed

    private void mnuItemCrearAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCrearAutorActionPerformed
        // TODO add your handling code here:
         desktopPanel.add(new VentanaCrearBuscarAutor());
    }//GEN-LAST:event_mnuItemCrearAutorActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new Principal().setVisible(true);
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MnuCrear;
    private javax.swing.JButton bBuscarLibro;
    private javax.swing.JButton bBuscarUsuario;
    private javax.swing.JButton bEditorial;
    private javax.swing.JButton bPrestar;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuItemCOsnultas;
    private javax.swing.JMenuItem mnuItemCrearAutor;
    private javax.swing.JMenuItem mnuItemCrearEditorial;
    private javax.swing.JMenuItem mnuItemCrearLobro;
    private javax.swing.JMenuItem mnuItemCrearUsuario;
    private javax.swing.JMenu mnuItemPrestamo;
    private javax.swing.JMenuItem mnuItemPrestar;
    private javax.swing.JMenuItem mnuSAlir;
    // End of variables declaration//GEN-END:variables

}
